#ifndef OPENMC_RANDOM_RAY_FLAT_SOURCE_DOMAIN_H
#define OPENMC_RANDOM_RAY_FLAT_SOURCE_DOMAIN_H

#include <map>
#include <algorithm>

#include "openmc/constants.h"
#include "openmc/openmp_interface.h"
#include "openmc/position.h"
#include "openmc/source.h"

namespace openmc {

//----------------------------------------------------------------------------
// Helper Functions

// The hash_combine function is the standard hash combine function from boost
// that is typically used for combining multiple hash values into a single hash
// as is needed for larger objects being stored in a hash map. The function is
// taken from:
// https://www.boost.org/doc/libs/1_55_0/doc/html/hash/reference.html#boost.hash_combine
// which carries the following license:
//
// Boost Software License - Version 1.0 - August 17th, 2003
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
inline void hash_combine(size_t& seed, const size_t v)
{
  seed ^= (v + 0x9e3779b9 + (seed << 6) + (seed >> 2));
}

//----------------------------------------------------------------------------
// Helper Structs

// A mapping object that is used to map between a specific random ray
// source region and an OpenMC native tally bin that it should score to
// every iteration.
struct TallyTask {
  int tally_idx;
  int filter_idx;
  int score_idx;
  int score_type;
  TallyTask(int tally_idx, int filter_idx, int score_idx, int score_type)
    : tally_idx(tally_idx), filter_idx(filter_idx), score_idx(score_idx),
      score_type(score_type)
  {}
  TallyTask() = default;

  // Comparison and Hash operators are defined to allow usage of the
  // TallyTask struct as a key in an unordered_set
  bool operator==(const TallyTask& other) const
  {
    return tally_idx == other.tally_idx && filter_idx == other.filter_idx &&
           score_idx == other.score_idx && score_type == other.score_type;
  }

  struct HashFunctor {
    size_t operator()(const TallyTask& task) const
    {
      size_t seed = 0;
      hash_combine(seed, task.tally_idx);
      hash_combine(seed, task.filter_idx);
      hash_combine(seed, task.score_idx);
      hash_combine(seed, task.score_type);
      return seed;
    }
  };
};

//----------------------------------------------------------------------------
// Helper Variables
// Coefficients come from Table 3 in Fornberg (1988)
// DOI: 10.1090/S0025-5718-1988-0935077-0
// Note that the signs are flipped compared to the citation, as the author was
// formulating weights for a forward difference
const std::map<int, vector<float>> bdf_coefficients_first_order_ = {
  {1, {1.0, -1.0}},
  {2, {1.5, -2.0, 0.5}},
  {3, {1.833333, -3.0, 1.5, -0.333333}},
  {4, {2.083333, -4.0, 3.0, -1.333333, 0.25}},
  {5, {2.283333, -5.0, 5.0, -3.333333, 1.25, -0.2}},
  {6, {2.45, -6.0, 7.5, -6.666666, 3.75, -1.2, 0.166666}}
};

// Coefficients come from Table 3 in Fornberg (1988)
// DOI: 10.1090/S0025-5718-1988-0935077-0
const std::map<int, vector<float>> bdf_coefficients_second_order_ = {
  {1, {1.0, -2.0, 1.0}},
  {2, {2.0, -5.0, 4, -1}},
  {3, {2.916666, -8.666666, 9.5, -4.666666, 0.916666}},
  {4, {3.75, -12.833333, 17.833333, -13.0, 5.083333, -0.833333}},
  {5, {4.511111, -17.4, 29.25, -28.222222, 16.5, -5.4, 0.761111}},
  {6, {5.211111, -22.3, 43.95, -52.722222, 41.0, -20.1, 5.661111, -0.7}}
};

/*
 * The FlatSourceDomain class encompasses data and methods for storing
 * scalar flux and source region for all flat source regions in a
 * random ray simulation domain.
 */

class FlatSourceDomain {
public:
  //----------------------------------------------------------------------------
  // Constructors and Destructors
  FlatSourceDomain();
  virtual ~FlatSourceDomain() = default;

  //----------------------------------------------------------------------------
  // Methods
  virtual void update_neutron_source(double k_eff);
  double compute_k_eff(double k_eff_old) const;
  virtual void normalize_scalar_flux_and_volumes(
    double total_active_distance_per_iteration);

  int64_t add_source_to_scalar_flux();
  virtual void batch_reset();
  void convert_source_regions_to_tallies();
  void reset_tally_volumes();
  void random_ray_tally();
  virtual void accumulate_iteration_flux();
  void output_to_vtk() const;
  virtual void all_reduce_replicated_source_regions();
  void convert_external_sources();
  void count_external_source_regions();
  void set_adjoint_sources(const vector<double>& forward_flux);
  virtual void flux_swap();
  virtual double evaluate_flux_at_point(Position r, int64_t sr, int g) const;
  double compute_fixed_source_normalization_factor() const;
  void flatten_xs();
  void transpose_scattering_matrix();
  void set_initial_condition(double k_eff_0);
  void compute_criticality_precursors(double k_eff_0);
  void update_material_density(int i);
  void compute_precursors(double k_eff_0, vector<double>& scalar_flux);
 
  //----------------------------------------------------------------------------
  // Static Data members
  static bool volume_normalized_flux_tallies_;
  static bool adjoint_; // If the user wants outputs based on the adjoint flux

  //----------------------------------------------------------------------------
  // Static data members
  static RandomRayVolumeEstimator volume_estimator_;

  //----------------------------------------------------------------------------
  // Public Data members

  bool mapped_all_tallies_ {false}; // If all source regions have been visited

  int64_t n_source_regions_ {0}; // Total number of source regions in the model
  int64_t n_external_source_regions_ {0}; // Total number of source regions with
                                          // non-zero external source terms
  int negroups_;                  // Number of energy groups in simulation
  int ndgroups_;                  // Number of delay groups in simulation
  int64_t n_source_elements_ {0}; // Total number of source regions in the model
                                  // times the number of energy group
  int64_t n_delay_elements_ {0};  // Total number of source regions in the model
                                  // times the number of delay groups
  int bdf_order_ {1}; // Order of BDF approximation for time-dependent
                      // simulations using SDP
  
  // 1D array representing source region starting offset for each OpenMC Cell
  // in model::cells
  vector<int64_t> source_region_offsets_;

  // 1D arrays representing values for all source regions
  vector<OpenMPMutex> lock_;
  vector<double> volume_;
  vector<double> volume_t_;
  vector<int> position_recorded_;
  vector<Position> position_;

  // 2D arrays stored in 1D representing values for all source regions x energy
  // groups
  vector<double> scalar_flux_old_;
  vector<double> scalar_flux_new_;
  vector<float> source_;
  vector<float> external_source_;
  vector<bool> external_source_present_;
  vector<double> scalar_flux_final_;

  // 2D arrays stored in 1D representing values for all source regions x delay
  // groups
  vector<double> precursors_;

  // 2D arrays stored in 1D representing values for all materials x energy
  // groups
  int n_materials_;
  vector<double> sigma_t_;
  vector<double> nu_sigma_f_;
  vector<double> sigma_f_;
  vector<double> chi_;
  vector<double> nu_p_sigma_f_;
  vector<double> chi_p_;
  vector<double> inverse_vbar_;

  // 2D arrays stored in 1D representing values for all materials x
  // delay_groups
  vector<double> lambda_;

  // 3D arrays stored in 1D representing values for all materials x energy
  // groups x energy groups
  vector<double> sigma_s_;

  // 3D arrays stored in 1D representing values for all materials x energy
  // groups x delay groups
  vector<double> nu_d_sigma_f_;
  vector<double> chi_d_;

  // Pointers to BDF vectors
  vector<double>* scalar_flux_bdf_;
  vector<float>* source_bdf_;
  vector<double>* precursors_bdf_;

protected:
  //----------------------------------------------------------------------------
  // Methods
  void apply_external_source_to_source_region(
    Discrete* discrete, double strength_factor, int64_t source_region);
  void apply_external_source_to_cell_instances(int32_t i_cell,
    Discrete* discrete, double strength_factor, int target_material_id,
    const vector<int32_t>& instances);
  void apply_external_source_to_cell_and_children(int32_t i_cell,
    Discrete* discrete, double strength_factor, int32_t target_material_id);
  virtual void set_flux_to_flux_plus_source(
    int64_t idx, double volume, int material, int g);
  void set_flux_to_source(int64_t idx, int material, int g);
  virtual void set_flux_to_old_flux(int64_t idx);

  //----------------------------------------------------------------------------
  // Private data members 
  double
    simulation_volume_; // Total physical volume of the simulation domain, as
                        // defined by the 3D box of the random ray source

  // 2D array representing values for all source elements x tally
  // tasks
  vector<vector<TallyTask>> tally_task_;

  // 1D array representing values for all source regions, with each region
  // containing a set of volume tally tasks. This more complicated data
  // structure is convenient for ensuring that volumes are only tallied once per
  // source region, regardless of how many energy groups are used for tallying.
  vector<std::unordered_set<TallyTask, TallyTask::HashFunctor>> volume_task_;

  // 1D arrays representing values for all source regions
  vector<int> material_;
  vector<double> volume_naive_;

  // Volumes for each tally and bin/score combination. This intermediate data
  // structure is used when tallying quantities that must be normalized by
  // volume (i.e., flux). The vector is index by tally index, while the inner 2D
  // xtensor is indexed by bin index and score index in a similar manner to the
  // results tensor in the Tally class, though without the third dimension, as
  // SUM and SUM_SQ do not need to be tracked.
  vector<xt::xtensor<double, 2>> tally_volumes_;

}; // class FlatSourceDomain

//============================================================================
//! Non-member functions
//============================================================================

// Returns the inputted value in big endian byte ordering. If the system is
// little endian, the byte ordering is flipped. If the system is big endian,
// the inputted value is returned as is. This function is necessary as
// .vtk binary files use big endian byte ordering.
template<typename T>
T convert_to_big_endian(T in)
{
  // 4 byte integer
  uint32_t test = 1;

  // 1 byte pointer to first byte of test integer
  uint8_t* ptr = reinterpret_cast<uint8_t*>(&test);

  // If the first byte of test is 0, then the system is big endian. In this
  // case, we don't have to do anything as .vtk files are big endian
  if (*ptr == 0)
    return in;

  // Otherwise, the system is in little endian, so we need to flip the
  // endianness
  uint8_t* orig = reinterpret_cast<uint8_t*>(&in);
  uint8_t swapper[sizeof(T)];
  for (int i = 0; i < sizeof(T); i++) {
    swapper[i] = orig[sizeof(T) - i - 1];
  }
  T out = *reinterpret_cast<T*>(&swapper);
  return out;
}

template<typename T>
void parallel_fill(vector<T>& arr, T value)
{
#pragma omp parallel for schedule(static)
  for (int i = 0; i < arr.size(); i++) {
    arr[i] = value;
  }
}

// BDF vector funtions
template<typename T>
T bdf_time_derivative(int index, vector<T>* bdf_vector, int bdf_order, double dt, int offset, int derivative_order = 1)
{
  vector<float> bdf_coeffs;
  int n_bdf_terms;
  double time_factor;
  if (derivative_order == 1) {
    bdf_coeffs = bdf_coefficients_first_order_.at(bdf_order);
    time_factor = 1 /  dt;
    n_bdf_terms = bdf_order + 1;
  } else if (derivative_order == 2) {
    bdf_coeffs = bdf_coefficients_second_order_.at(bdf_order);
    n_bdf_terms = bdf_order + 2;
    time_factor = 1 / (dt * dt);
  } else {
    fatal_error("Only first or second order BDF derivatives are allowed.");
  }
  T bdf_derivative = 0.0;
  for (int i = 0; i < n_bdf_terms; i++) {
    float coeff = bdf_coeffs[i];
    T x = (*bdf_vector)[index + i * offset]; // n_source_elements_ in most cases
    bdf_derivative += coeff * x * time_factor;
  }
  return bdf_derivative;
}

// Update the first n elements of bdf_vector with
// all n elements of  new_solution.
// Optionally scale rotate bdf_vector so the last n
// elements are moved to the first n elements
// before updating.
// Optionally scale the new solutions by factor
template<typename T>
void update_bdf_vector(vector<T>* bdf_vector, vector<T>& new_solution, bool increment, T factor = 1)
{ 
  int n = new_solution.size();
  // Move the oldest solution to the front of the vector
  if (increment) 
    rotate(bdf_vector->rbegin(), bdf_vector->rbegin() + n, bdf_vector->rend());
  // Replace the oldest solution with the new solution
  for (int i = 0; i < n; i++)
    (*bdf_vector)[i] = new_solution[i] * factor;
}


template<typename T>
T rhs_backwards_difference(vector<T>* bdf_vector, int64_t vector_size, int idx, const vector<float>& bdf_coeffs, double dt)
{ 
    int bdf_order = bdf_coeffs.size() - 1;
    T rhs_bdf = 0.0;
    for (int j = 1; j <= bdf_order; j++)
      rhs_bdf += bdf_coeffs[j] * (*bdf_vector)[idx + j * vector_size];
    rhs_bdf /= dt;
    return rhs_bdf;
}

} // namespace openmc

#endif // OPENMC_RANDOM_RAY_FLAT_SOURCE_DOMAIN_H
