#ifndef OPENMC_RANDOM_RAY_SOURCE_REGION_H
#define OPENMC_RANDOM_RAY_SOURCE_REGION_H

#include <deque>

#include "openmc/openmp_interface.h"
#include "openmc/position.h"
#include "openmc/random_ray/moment_matrix.h"
#include "openmc/settings.h"

namespace openmc {

//----------------------------------------------------------------------------
// Helper Functions

// The hash_combine function is the standard hash combine function from boost
// that is typically used for combining multiple hash values into a single hash
// as is needed for larger objects being stored in a hash map. The function is
// taken from:
// https://www.boost.org/doc/libs/1_55_0/doc/html/hash/reference.html#boost.hash_combine
// which carries the following license:
//
// Boost Software License - Version 1.0 - August 17th, 2003
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
inline void hash_combine(size_t& seed, const size_t v)
{
  seed ^= (v + 0x9e3779b9 + (seed << 6) + (seed >> 2));
}

//----------------------------------------------------------------------------
// Helper Structs

// A mapping object that is used to map between a specific random ray
// source region and an OpenMC native tally bin that it should score to
// every iteration.
struct TallyTask {
  int tally_idx;
  int filter_idx;
  int score_idx;
  int score_type;
  TallyTask(int tally_idx, int filter_idx, int score_idx, int score_type)
    : tally_idx(tally_idx), filter_idx(filter_idx), score_idx(score_idx),
      score_type(score_type)
  {}
  TallyTask() = default;

  // Comparison and Hash operators are defined to allow usage of the
  // TallyTask struct as a key in an unordered_set
  bool operator==(const TallyTask& other) const
  {
    return tally_idx == other.tally_idx && filter_idx == other.filter_idx &&
           score_idx == other.score_idx && score_type == other.score_type;
  }

  struct HashFunctor {
    size_t operator()(const TallyTask& task) const
    {
      size_t seed = 0;
      hash_combine(seed, task.tally_idx);
      hash_combine(seed, task.filter_idx);
      hash_combine(seed, task.score_idx);
      hash_combine(seed, task.score_type);
      return seed;
    }
  };
};

class SourceRegion {
public:
  //----------------------------------------------------------------------------
  // Constructors
  SourceRegion(int negroups, int ndgroups, bool is_linear);
  SourceRegion() = default;

  //----------------------------------------------------------------------------
  // Public Data members

  // Scalar fields
  int material_ {0};
  OpenMPMutex lock_;
  double volume_ {0.0};
  double volume_t_ {0.0};
  double volume_naive_ {0.0};
  int position_recorded_ {0};
  int external_source_present_ {0};
  Position position_ {0.0, 0.0, 0.0};
  Position centroid_ {0.0, 0.0, 0.0};
  Position centroid_iteration_ {0.0, 0.0, 0.0};
  Position centroid_t_ {0.0, 0.0, 0.0};
  MomentMatrix mom_matrix_ {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
  MomentMatrix mom_matrix_t_ {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
  // A set of volume tally tasks. This more complicated data structure is
  // convenient for ensuring that volumes are only tallied once per source
  // region, regardless of how many energy groups are used for tallying.
  std::unordered_set<TallyTask, TallyTask::HashFunctor> volume_task_;

  // Energy group-wise 1D arrays
  vector<double> scalar_flux_old_;
  vector<double> scalar_flux_new_;
  vector<double> source_;
  vector<float> external_source_;
  vector<double> scalar_flux_final_;

  vector<MomentArray> source_gradients_;
  vector<MomentArray> flux_moments_old_;
  vector<MomentArray> flux_moments_new_;
  vector<MomentArray> flux_moments_t_;

  // Energy group-wise 1D time-dependent arrrays
  vector<double> source_final_;       //!< The total source accumulated over all
                                      //!< active iterations (used for SDP)
  vector<double> scalar_flux_td_old_; //!< The time-dependent scalar flux from
                                      //!< the previous iteration
  vector<double> scalar_flux_td_new_; //!< The time-dependent scalar flux from
                                      //!< the current iteration
  vector<double>
    scalar_flux_td_final_; //!< The time-dependent scalar flux accumulated over
                           //!< all active iterations (used as the initial
                           //!< condition for the next timestep)

  vector<double> source_td_; //!< The total time-dependent source term (prompt
                             //!< fission + scattering + delayed emission)
  vector<double>
    source_td_final_; //!< The total time-dependent source accumulated over all
                      //!< active iterations (used for SDP)

  // Energy group-wise 1D derivative arrays
  vector<double> source_time_derivative_;        //!< The time derivative of the
                                                 //!< source (used for SDP)
  vector<double> scalar_flux_time_derivative_2_; //!< The 2nd order time
                                                 //!< derivative of the scalar
                                                 //!< flux (used for SDP)
  // Delay group-wise 1D arrays
  vector<double> precursors_old_; //!< The precursor density from the previous
                                  //!< iteration. Currently unused
  vector<double>
    precursors_new_; //!< The precursor density fro the current iteration
  vector<double>
    precursors_final_; //!< The precursor density accumulated over all
                       //!< active iterations (used for computing
                       //!< the time derivative of precursor density)

  vector<double>
    delayed_fission_source_; //!< The delayed fission source binned by delay
                             //!< group (used for Precursor Integration)

  // Precursor Integration arrays
  vector<double>
    delayed_fission_source_final_; //!< The delayed fission source accumulated
                                   //!< over all active iterations (used for
                                   //!< computing Precursor Integration)

  vector<double> precursors_im1_; //!< Precursor solution from previous time
                                  //!< step. Used to solve the precursor
                                  //!< equation using the integration method.
  vector<double> delayed_fission_source_im1_; //<! Delayed fission source from
                                              // the previous time step.
                                              //<! Used to solve the precursor
                                              // equation using the
                                              //<! integration method.
  vector<double> delayed_fission_source_im2_; //<! Delayed fission source from
                                              // the i-2 time step.
                                              //<! Used to solve the precursor
                                              // equation using the
                                              //<! integration method.

  // BD arrays
  std::deque<double> scalar_flux_bd_;
  std::deque<double> precursors_bd_;
  std::deque<double> source_bd_;

  // Energy group-wise 1D RHS BD arrays
  vector<double>
    scalar_flux_rhs_bd_; //!< RHS dervative for the scalar flux from previous
                         //!< timesteps. Used to compute the total scalar flux
                         //!< time derivative for both TI and SDP time-dependent
                         //!< simulations
  vector<double> source_rhs_bd_; //!< RHS derivative for the neutron source from
                                 //!< previous timesteps Used for compute the
                                 //!< total neutron source derivative for SDP
  vector<double>
    scalar_flux_rhs_bd_2_; //!< 2nd order RHS derivative for the scalar flux
                           //!< from previous timesteps. Used to compute the
                           //!< total 2nd order scalar flux time derivative for
                           //!< SDP.

  // Delay group-wise 1D RHS BD arrays
  vector<double>
    precursors_rhs_bd_; //!< RHS derivative for the precursors from previous
                        //!< timesteps. Used to compute the total precursor time
                        //!< derivative for solving the precursor equation using
                        //!< backwards differences.

  // 2D array representing values for all energy groups x tally
  // tasks. Each group may have a different number of tally tasks
  // associated with it, necessitating the use of a jagged array.
  vector<vector<TallyTask>> tally_task_;

  // 2D array representing values for all delay groups x tally
  // tasks. Each group may have a different number of tally tasks
  // associated with it, necessitating the use of a jagged array.
  vector<vector<TallyTask>> tally_delay_task_;

  // 1D array representing fission source across a fixed window of batches.
  // This is used for assesing source convergence.
  std::deque<double> batchwise_fission_source_;

}; // class SourceRegion

class SourceRegionContainer {
public:
  //----------------------------------------------------------------------------
  // Constructors
  SourceRegionContainer(int negroups, int ndgroups, bool is_linear)
    : negroups_(negroups), ndgroups_(ndgroups), is_linear_(is_linear)
  {}
  SourceRegionContainer() = default;

  //----------------------------------------------------------------------------
  // Public Accessors
  int& material(int64_t sr) { return material_[sr]; }
  const int& material(int64_t sr) const { return material_[sr]; }

  OpenMPMutex& lock(int64_t sr) { return lock_[sr]; }
  const OpenMPMutex& lock(int64_t sr) const { return lock_[sr]; }

  double& volume(int64_t sr) { return volume_[sr]; }
  const double& volume(int64_t sr) const { return volume_[sr]; }

  double& volume_t(int64_t sr) { return volume_t_[sr]; }
  const double& volume_t(int64_t sr) const { return volume_t_[sr]; }

  double& volume_naive(int64_t sr) { return volume_naive_[sr]; }
  const double& volume_naive(int64_t sr) const { return volume_naive_[sr]; }

  int& position_recorded(int64_t sr) { return position_recorded_[sr]; }
  const int& position_recorded(int64_t sr) const
  {
    return position_recorded_[sr];
  }

  int& external_source_present(int64_t sr)
  {
    return external_source_present_[sr];
  }
  const int& external_source_present(int64_t sr) const
  {
    return external_source_present_[sr];
  }

  Position& position(int64_t sr) { return position_[sr]; }
  const Position& position(int64_t sr) const { return position_[sr]; }

  Position& centroid(int64_t sr) { return centroid_[sr]; }
  const Position& centroid(int64_t sr) const { return centroid_[sr]; }

  Position& centroid_iteration(int64_t sr) { return centroid_iteration_[sr]; }
  const Position& centroid_iteration(int64_t sr) const
  {
    return centroid_iteration_[sr];
  }

  Position& centroid_t(int64_t sr) { return centroid_t_[sr]; }
  const Position& centroid_t(int64_t sr) const { return centroid_t_[sr]; }

  MomentMatrix& mom_matrix(int64_t sr) { return mom_matrix_[sr]; }
  const MomentMatrix& mom_matrix(int64_t sr) const { return mom_matrix_[sr]; }

  MomentMatrix& mom_matrix_t(int64_t sr) { return mom_matrix_t_[sr]; }
  const MomentMatrix& mom_matrix_t(int64_t sr) const
  {
    return mom_matrix_t_[sr];
  }

  MomentArray& source_gradients(int64_t sr, int g)
  {
    return source_gradients_[index(sr, g)];
  }
  const MomentArray& source_gradients(int64_t sr, int g) const
  {
    return source_gradients_[index(sr, g)];
  }
  MomentArray& source_gradients(int64_t se) { return source_gradients_[se]; }
  const MomentArray& source_gradients(int64_t se) const
  {
    return source_gradients_[se];
  }

  MomentArray& flux_moments_old(int64_t sr, int g)
  {
    return flux_moments_old_[index(sr, g)];
  }
  const MomentArray& flux_moments_old(int64_t sr, int g) const
  {
    return flux_moments_old_[index(sr, g)];
  }
  MomentArray& flux_moments_old(int64_t se) { return flux_moments_old_[se]; }
  const MomentArray& flux_moments_old(int64_t se) const
  {
    return flux_moments_old_[se];
  }

  MomentArray& flux_moments_new(int64_t sr, int g)
  {
    return flux_moments_new_[index(sr, g)];
  }
  const MomentArray& flux_moments_new(int64_t sr, int g) const
  {
    return flux_moments_new_[index(sr, g)];
  }
  MomentArray& flux_moments_new(int64_t se) { return flux_moments_new_[se]; }
  const MomentArray& flux_moments_new(int64_t se) const
  {
    return flux_moments_new_[se];
  }

  MomentArray& flux_moments_t(int64_t sr, int g)
  {
    return flux_moments_t_[index(sr, g)];
  }
  const MomentArray& flux_moments_t(int64_t sr, int g) const
  {
    return flux_moments_t_[index(sr, g)];
  }
  MomentArray& flux_moments_t(int64_t se) { return flux_moments_t_[se]; }
  const MomentArray& flux_moments_t(int64_t se) const
  {
    return flux_moments_t_[se];
  }

  double& scalar_flux_old(int64_t sr, int g)
  {
    return scalar_flux_old_[index(sr, g)];
  }
  const double& scalar_flux_old(int64_t sr, int g) const
  {
    return scalar_flux_old_[index(sr, g)];
  }
  double& scalar_flux_old(int64_t se) { return scalar_flux_old_[se]; }
  const double& scalar_flux_old(int64_t se) const
  {
    return scalar_flux_old_[se];
  }

  double& scalar_flux_new(int64_t sr, int g)
  {
    return scalar_flux_new_[index(sr, g)];
  }
  const double& scalar_flux_new(int64_t sr, int g) const
  {
    return scalar_flux_new_[index(sr, g)];
  }
  double& scalar_flux_new(int64_t se) { return scalar_flux_new_[se]; }
  const double& scalar_flux_new(int64_t se) const
  {
    return scalar_flux_new_[se];
  }

  double& scalar_flux_final(int64_t sr, int g)
  {
    return scalar_flux_final_[index(sr, g)];
  }
  const double& scalar_flux_final(int64_t sr, int g) const
  {
    return scalar_flux_final_[index(sr, g)];
  }
  double& scalar_flux_final(int64_t se) { return scalar_flux_final_[se]; }
  const double& scalar_flux_final(int64_t se) const
  {
    return scalar_flux_final_[se];
  }

  double& source(int64_t sr, int g) { return source_[index(sr, g)]; }
  const double& source(int64_t sr, int g) const { return source_[index(sr, g)]; }
  double& source(int64_t se) { return source_[se]; }
  const double& source(int64_t se) const { return source_[se]; }

  double& source_final(int64_t sr, int g)
  {
    return source_final_[index(sr, g)];
  }
  const double& source_final(int64_t sr, int g) const
  {
    return source_final_[index(sr, g)];
  }
  double& source_final(int64_t se) { return source_final_[se]; }
  const double& source_final(int64_t se) const { return source_final_[se]; }

  double& scalar_flux_td_old(int64_t sr, int g)
  {
    return scalar_flux_td_old_[index(sr, g)];
  }
  const double& scalar_flux_td_old(int64_t sr, int g) const
  {
    return scalar_flux_td_old_[index(sr, g)];
  }
  double& scalar_flux_td_old(int64_t se) { return scalar_flux_td_old_[se]; }
  const double& scalar_flux_td_old(int64_t se) const
  {
    return scalar_flux_td_old_[se];
  }

  double& scalar_flux_td_new(int64_t sr, int g)
  {
    return scalar_flux_td_new_[index(sr, g)];
  }
  const double& scalar_flux_td_new(int64_t sr, int g) const
  {
    return scalar_flux_td_new_[index(sr, g)];
  }
  double& scalar_flux_td_new(int64_t se) { return scalar_flux_td_new_[se]; }
  const double& scalar_flux_td_new(int64_t se) const
  {
    return scalar_flux_td_new_[se];
  }

  double& scalar_flux_td_final(int64_t sr, int g)
  {
    return scalar_flux_td_final_[index(sr, g)];
  }
  const double& scalar_flux_td_final(int64_t sr, int g) const
  {
    return scalar_flux_td_final_[index(sr, g)];
  }
  double& scalar_flux_td_final(int64_t se) { return scalar_flux_td_final_[se]; }
  const double& scalar_flux_td_final(int64_t se) const
  {
    return scalar_flux_td_final_[se];
  }

  double& source_td(int64_t sr, int g) { return source_td_[index(sr, g)]; }
  const double& source_td(int64_t sr, int g) const { return source_td_[index(sr, g)]; }
  double& source_td(int64_t se) { return source_td_[se]; }
  const double& source_td(int64_t se) const { return source_td_[se]; }

  double& source_td_final(int64_t sr, int g)
  {
    return source_td_final_[index(sr, g)];
  }
  const double& source_td_final(int64_t sr, int g) const
  {
    return source_td_final_[index(sr, g)];
  }
  double& source_td_final(int64_t se) { return source_td_final_[se]; }
  const double& source_td_final(int64_t se) const
  {
    return source_td_final_[se];
  }

  double& source_time_derivative(int64_t sr, int g)
  {
    return source_time_derivative_[index(sr, g)];
  }
  const double& source_time_derivative(int64_t sr, int g) const
  {
    return source_time_derivative_[index(sr, g)];
  }
  double& source_time_derivative(int64_t se)
  {
    return source_time_derivative_[se];
  }
  const double& source_time_derivative(int64_t se) const
  {
    return source_time_derivative_[se];
  }

  double& scalar_flux_time_derivative_2(int64_t sr, int g)
  {
    return scalar_flux_time_derivative_2_[index(sr, g)];
  }
  const double& scalar_flux_time_derivative_2(int64_t sr, int g) const
  {
    return scalar_flux_time_derivative_2_[index(sr, g)];
  }
  double& scalar_flux_time_derivative_2(int64_t se)
  {
    return scalar_flux_time_derivative_2_[se];
  }
  const double& scalar_flux_time_derivative_2(int64_t se) const
  {
    return scalar_flux_time_derivative_2_[se];
  }

  double& precursors_old(int64_t sr, int dg)
  {
    return precursors_old_[dindex(sr, dg)];
  }
  const double& precursors_old(int64_t sr, int dg) const
  {
    return precursors_old_[dindex(sr, dg)];
  }
  double& precursors_old(int64_t de) { return precursors_old_[de]; }
  const double& precursors_old(int64_t de) const { return precursors_old_[de]; }

  double& precursors_new(int64_t sr, int dg)
  {
    return precursors_new_[dindex(sr, dg)];
  }
  const double& precursors_new(int64_t sr, int dg) const
  {
    return precursors_new_[dindex(sr, dg)];
  }
  double& precursors_new(int64_t de) { return precursors_new_[de]; }
  const double& precursors_new(int64_t de) const { return precursors_new_[de]; }

  double& precursors_final(int64_t sr, int dg)
  {
    return precursors_final_[dindex(sr, dg)];
  }
  const double& precursors_final(int64_t sr, int dg) const
  {
    return precursors_final_[dindex(sr, dg)];
  }
  double& precursors_final(int64_t de) { return precursors_final_[de]; }
  const double& precursors_final(int64_t de) const
  {
    return precursors_final_[de];
  }

  double& delayed_fission_source(int64_t sr, int dg)
  {
    return delayed_fission_source_[dindex(sr, dg)];
  }
  const double& delayed_fission_source(int64_t sr, int dg) const
  {
    return delayed_fission_source_[dindex(sr, dg)];
  }
  double& delayed_fission_source(int64_t de)
  {
    return delayed_fission_source_[de];
  }
  const double& delayed_fission_source(int64_t de) const
  {
    return delayed_fission_source_[de];
  }

  double& delayed_fission_source_final(int64_t sr, int dg)
  {
    return delayed_fission_source_final_[dindex(sr, dg)];
  }
  const double& delayed_fission_source_final(int64_t sr, int dg) const
  {
    return delayed_fission_source_final_[dindex(sr, dg)];
  }
  double& delayed_fission_source_final(int64_t de)
  {
    return delayed_fission_source_final_[de];
  }
  const double& delayed_fission_source_final(int64_t de) const
  {
    return delayed_fission_source_final_[de];
  }

  std::deque<double>& scalar_flux_bd(int64_t sr, int g)
  {
    return scalar_flux_bd_[index(sr, g)];
  }
  const std::deque<double>& scalar_flux_bd(int64_t sr, int g) const
  {
    return scalar_flux_bd_[index(sr, g)];
  }
  std::deque<double>& scalar_flux_bd(int64_t se) { return scalar_flux_bd_[se]; }
  const std::deque<double>& scalar_flux_bd(int64_t se) const
  {
    return scalar_flux_bd_[se];
  }

  std::deque<double>& precursors_bd(int64_t sr, int dg)
  {
    return precursors_bd_[dindex(sr, dg)];
  }
  const std::deque<double>& precursors_bd(int64_t sr, int dg) const
  {
    return precursors_bd_[dindex(sr, dg)];
  }
  std::deque<double>& precursors_bd(int64_t de) { return precursors_bd_[de]; }
  const std::deque<double>& precursors_bd(int64_t de) const
  {
    return precursors_bd_[de];
  }

  std::deque<double>& source_bd(int64_t sr, int g)
  {
    return source_bd_[index(sr, g)];
  }
  const std::deque<double>& source_bd(int64_t sr, int g) const
  {
    return source_bd_[index(sr, g)];
  }
  std::deque<double>& source_bd(int64_t se) { return source_bd_[se]; }
  const std::deque<double>& source_bd(int64_t se) const
  {
    return source_bd_[se];
  }

  double& scalar_flux_rhs_bd(int64_t sr, int g)
  {
    return scalar_flux_rhs_bd_[index(sr, g)];
  }
  const double& scalar_flux_rhs_bd(int64_t sr, int g) const
  {
    return scalar_flux_rhs_bd_[index(sr, g)];
  }
  double& scalar_flux_rhs_bd(int64_t se) { return scalar_flux_rhs_bd_[se]; }
  const double& scalar_flux_rhs_bd(int64_t se) const
  {
    return scalar_flux_rhs_bd_[se];
  }

  double& precursors_rhs_bd(int64_t sr, int dg)
  {
    return precursors_rhs_bd_[dindex(sr, dg)];
  }
  const double& precursors_rhs_bd(int64_t sr, int dg) const
  {
    return precursors_rhs_bd_[dindex(sr, dg)];
  }
  double& precursors_rhs_bd(int64_t de) { return precursors_rhs_bd_[de]; }
  const double& precursors_rhs_bd(int64_t de) const
  {
    return precursors_rhs_bd_[de];
  }

  double& source_rhs_bd(int64_t sr, int g)
  {
    return source_rhs_bd_[index(sr, g)];
  }
  const double& source_rhs_bd(int64_t sr, int g) const
  {
    return source_rhs_bd_[index(sr, g)];
  }
  double& source_rhs_bd(int64_t se) { return source_rhs_bd_[se]; }
  const double& source_rhs_bd(int64_t se) const { return source_rhs_bd_[se]; }

  double& scalar_flux_rhs_bd_2(int64_t sr, int g)
  {
    return scalar_flux_rhs_bd_2_[index(sr, g)];
  }
  const double& scalar_flux_rhs_bd_2(int64_t sr, int g) const
  {
    return scalar_flux_rhs_bd_2_[index(sr, g)];
  }
  double& scalar_flux_rhs_bd_2(int64_t se) { return scalar_flux_rhs_bd_2_[se]; }
  const double& scalar_flux_rhs_bd_2(int64_t se) const
  {
    return scalar_flux_rhs_bd_2_[se];
  }

  double& precursors_im1(int64_t sr, int dg)
  {
    return precursors_im1_[dindex(sr, dg)];
  }
  const double& precursors_im1(int64_t sr, int dg) const
  {
    return precursors_im1_[dindex(sr, dg)];
  }
  double& precursors_im1(int64_t de) { return precursors_im1_[de]; }
  const double& precursors_im1(int64_t de) const { return precursors_im1_[de]; }

  double& delayed_fission_source_im1(int64_t sr, int dg)
  {
    return delayed_fission_source_im1_[dindex(sr, dg)];
  }
  const double& delayed_fission_source_im1(int64_t sr, int dg) const
  {
    return delayed_fission_source_im1_[dindex(sr, dg)];
  }
  double& delayed_fission_source_im1(int64_t de)
  {
    return delayed_fission_source_im1_[de];
  }
  const double& delayed_fission_source_im1(int64_t de) const
  {
    return delayed_fission_source_im1_[de];
  }

  double& delayed_fission_source_im2(int64_t sr, int dg)
  {
    return delayed_fission_source_im2_[dindex(sr, dg)];
  }
  const double& delayed_fission_source_im2(int64_t sr, int dg) const
  {
    return delayed_fission_source_im2_[dindex(sr, dg)];
  }
  double& delayed_fission_source_im2(int64_t de)
  {
    return delayed_fission_source_im2_[de];
  }
  const double& delayed_fission_source_im2(int64_t de) const
  {
    return delayed_fission_source_im2_[de];
  }

  float& external_source(int64_t sr, int g)
  {
    return external_source_[index(sr, g)];
  }
  const float& external_source(int64_t sr, int g) const
  {
    return external_source_[index(sr, g)];
  }
  float& external_source(int64_t se) { return external_source_[se]; }
  const float& external_source(int64_t se) const
  {
    return external_source_[se];
  }

  vector<TallyTask>& tally_task(int64_t sr, int g)
  {
    return tally_task_[index(sr, g)];
  }
  const vector<TallyTask>& tally_task(int64_t sr, int g) const
  {
    return tally_task_[index(sr, g)];
  }
  vector<TallyTask>& tally_task(int64_t se) { return tally_task_[se]; }
  const vector<TallyTask>& tally_task(int64_t se) const
  {
    return tally_task_[se];
  }

  vector<TallyTask>& tally_delay_task(int64_t sr, int dg)
  {
    return tally_delay_task_[dindex(sr, dg)];
  }
  const vector<TallyTask>& tally_delay_task(int64_t sr, int dg) const
  {
    return tally_delay_task_[dindex(sr, dg)];
  }
  vector<TallyTask>& tally_delay_task(int64_t de)
  {
    return tally_delay_task_[de];
  }
  const vector<TallyTask>& tally_delay_task(int64_t de) const
  {
    return tally_delay_task_[de];
  }

  std::deque<double>& batchwise_fission_source(int64_t sr)
  {
    return batchwise_fission_source_[sr];
  }
  const std::deque<double>& batchwise_fission_source(int64_t sr) const
  {
    return batchwise_fission_source_[sr];
  }

  std::unordered_set<TallyTask, TallyTask::HashFunctor>& volume_task(int64_t sr)
  {
    return volume_task_[sr];
  }
  const std::unordered_set<TallyTask, TallyTask::HashFunctor>& volume_task(
    int64_t sr) const
  {
    return volume_task_[sr];
  }

  //----------------------------------------------------------------------------
  // Public Methods

  void push_back(const SourceRegion& sr);
  void assign(int n_source_regions, const SourceRegion& source_region);
  void flux_swap();
  void mpi_sync_ranks(bool reduce_position);

  // Time-dependent methods
  void flux_td_swap();
  void precursors_swap();

private:
  //----------------------------------------------------------------------------
  // Private Data Members
  int64_t n_source_regions_ {0};
  int negroups_ {0};
  int ndgroups_ {0};
  bool is_linear_ {false};

  // SoA storage for scalar fields (one item per source region)
  vector<int> material_;
  vector<OpenMPMutex> lock_;
  vector<double> volume_;
  vector<double> volume_t_;
  vector<double> volume_naive_;
  vector<int> position_recorded_;
  vector<int> external_source_present_;
  vector<Position> position_;
  vector<Position> centroid_;
  vector<Position> centroid_iteration_;
  vector<Position> centroid_t_;
  vector<MomentMatrix> mom_matrix_;
  vector<MomentMatrix> mom_matrix_t_;
  // A set of volume tally tasks. This more complicated data structure is
  // convenient for ensuring that volumes are only tallied once per source
  // region, regardless of how many energy groups are used for tallying.
  vector<std::unordered_set<TallyTask, TallyTask::HashFunctor>> volume_task_;

  // SoA energy group-wise 2D arrays flattened to 1D
  vector<double> scalar_flux_old_;
  vector<double> scalar_flux_new_;
  vector<double> scalar_flux_final_;
  vector<double> source_;
  vector<double> source_final_;
  vector<float> external_source_;

  vector<MomentArray> source_gradients_;
  vector<MomentArray> flux_moments_old_;
  vector<MomentArray> flux_moments_new_;
  vector<MomentArray> flux_moments_t_;

  // SoA energy group-wise 2D time-dependent arrays flattened to 1D
  vector<double> scalar_flux_td_old_;
  vector<double> scalar_flux_td_new_;
  vector<double> scalar_flux_td_final_;

  vector<double> source_td_;
  vector<double> source_td_final_;

  // SoA energy group-wise 2D derivative arrays flattened to 1D
  vector<double> source_time_derivative_;
  vector<double> scalar_flux_time_derivative_2_;

  // SoA delay group-wise 2D arrays flattened to 1D
  vector<double> precursors_old_;
  vector<double> precursors_new_;
  vector<double> precursors_final_;
  vector<double> delayed_fission_source_;
  vector<double> delayed_fission_source_final_;

  vector<double> precursors_im1_;
  vector<double> delayed_fission_source_im1_;
  vector<double> delayed_fission_source_im2_;

  // SoA energy group-wise 2D BD arrays flattened to 1D
  vector<std::deque<double>> scalar_flux_bd_;
  vector<std::deque<double>> precursors_bd_;
  vector<std::deque<double>> source_bd_;

  // SoA energy group-wise 2D RHS BD arrays flattened to 1D
  vector<double> scalar_flux_rhs_bd_;
  vector<double> source_rhs_bd_;
  vector<double> scalar_flux_rhs_bd_2_;

  // SoA delay group-wise 2D RHS BD arrays flattened to 1D
  vector<double> precursors_rhs_bd_;

  // SoA 3D array representing values for all source regions x energy groups x
  // tally tasks. The outer two dimensions (source regions and energy groups)
  // are flattened to 1D. Each group may have a different number of tally tasks
  // associated with it, necessitating the use of a jagged array for the inner
  // dimension.
  vector<vector<TallyTask>> tally_task_;

  // SoA 3D array representing values for all source regions x delay groups x
  // tally tasks. The outer two dimensions (source regions and delay groups)
  // are flattened to 1D. Each group may have a different number of tally tasks
  // associated with it, necessitating the use of a jagged array for the inner
  // dimension.
  vector<vector<TallyTask>> tally_delay_task_;

  // SoA source region-wise 2D batchwise fission source array
  vector<std::deque<double>> batchwise_fission_source_;

  //----------------------------------------------------------------------------
  // Private Methods

  // Helper function for indexing
  inline int index(int64_t sr, int g) const { return sr * negroups_ + g; }
  inline int dindex(int64_t sr, int dg) const { return sr * ndgroups_ + dg; }
};

} // namespace openmc

#endif // OPENMC_RANDOM_RAY_SOURCE_REGION_H
